name: NutriScan App Build

on:
  push:
    branches: [ "principal", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Guardar paquete de app
        uses: actions/upload-artifact@v3
        with:
          name: NutriScan-App
          path: Actividad principal.kt
