name: Compilar APK NutriScan

on:
  push:
    branches: [ "principal", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Guardar código ejecutable
        run: |
          mkdir -p app/src/main/java/com/nutriscan
          cp MainActivity.kt app/src/main/java/com/nutriscan/

      - name: Subir artefacto APK
        uses: actions/upload-artifact@v3
        with:
          name: NutriScan-App
          path: MainActivity.kt
