name: Build NutriScan APK

on:
  push:
    branches: [ "principal", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Upload Source
        uses: actions/upload-artifact@v3
        with:
          name: NutriScan-App
          path: MainActivity.kt
